config/routes.rb
Rails.application.routes.draw do

  root 'photos#index'
  resources :photos

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  scope :newest_first, -> { order(created_at: :desc )}
  scope :most_recent_five, -> { newest_first.limit(5) }
  scope :created_before, ->(time) { where("created_at < ?", time) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # Instructs the Controller to Handle Record Not Found requests with the not found method.
  rescue_from ActiveRecord::RecordNotFound, with: :not_found


  def show
    @photo = Photo.find(params[:id])
  end

  def index
    @photo = Photo.newest_first
  end

  def create
    if @photo
      flash[:notice] = 'New Photo Created'
      redirect_to photo_path(@photo)
    else
      flash[:error] = 'Failed to Create Photo'
      redirect_to new
    end
  end

  def new
    @photo = Photo.new
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def update
    @photo = Photo.find(params[:id])
    if @photo.update_attributes(post_params)
      flash[:notice] = "Photo #{params[:id]} updated."
      redirect_to photo_path(@photo)
    else
      flash[:error] = "Photo #{params[:id]} not updated."
      redirect_to edit_photo_path(@photo)
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to photos_path
  end

  private
  def post_params
    params.require(:photo).permit(:title, :author, :url)
  end

  def not_found
      flash[:error] = "Photo #{params[:id]} not found"
      redirect_to photos_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def class_for_item(symbol)
    puts "Class for Symbol #{symbol}, of type #{symbol.class}"
    case symbol
      when 'error'
        puts 'Trigger Error'
        'alert alert-danger'
      when 'notice'
        puts 'Trigger Notice'
        'alert alert-success'
    end
  end

  def badge_text
    #to_s required as the values will not convert automatically.
    Photo.count.to_s + '/' + Photo.created_before(1.month.ago).count.to_s
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
  def list_group_link(path,text,classes,badge)
    if current_page?(path)
      # Necessary to state partial, otherwise locals are not passed to partial.
      render partial: 'list_item_current', locals: {path: path, text: text, classes: classes, badge: badge}
    else
      render partial: 'list_item_standard', locals: {path: path, text: text, classes: classes, badge: badge}
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photogur</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'bootstrap' %>
  <%= stylesheet_link_tag 'http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div class="row">
    <header>
      <h1>Photogur<small><%= yield :head %></small></h1>
      <% flash.each do |name, msg| -%>
          <%= content_tag :div, msg, class: class_for_item(name) %>
      <% end -%>
    </header>
  </div>
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <%= list_group_link(new_photo_path, 'New Photo', 'fa fa-fw fa-pencil',nil) %>
        <%= list_group_link(photos_path, 'All Photos', 'fa fa-fw fa-list', badge_text) %>
      </div>
    </div>
    <div class="col-md-9"><%= yield %></div>
  </div>
</div>
</body>
</html>

app/views/photos/_list_item_current.html.erb
<div class="list-group-item disabled">
  <span class="<%= classes %>"></span>
  <%= content_tag :span, text %>
  <% if !badge.nil? %>
      <%= content_tag :span, badge, class: 'badge' %>
  <% end %>
</div>

app/views/photos/_list_item_standard.html.erb
<%= link_to path, class: "list-group-item" do %>
    <span class="<%= classes %>"></span>
    <%= content_tag :span, text %>
    <% if !badge.nil? %>
        <%= content_tag :span, badge, class: 'badge' %>
    <% end %>
<% end %>

app/views/photos/_photos_form.html.erb
<%= form_for @photo, html: {class: 'form-horizontal'} do |f| %>

    <div class="form-group"><%= label @photo, :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group"><%= label @photo, :author %>
      <%= f.text_field :author, class: 'form-control' %>
    </div>
    <div class="form-group"><%= label @photo, :url %>
      <%= f.text_field :url, class: 'form-control' %></div>
    <div class="form-group"><%= f.submit class: 'btn btn-primary' %></div>

<% end %>

app/views/photos/edit.html.erb
<% content_for :head do %>
    Edit Photo
<% end %>
<%= render'photos_form' %>

app/views/photos/index.html.erb
<% content_for :head do %>
    All Photos
<% end %>

<% @photo.each do |photo| %>
    <div class="col-md-3">
      <%= link_to image_tag(photo.url, class: 'img-responsive'), photo_path(photo) %>
      <%= content_tag :div, photo.title, class: 'photo_title' %>
      <%= content_tag :div, photo.author, class: 'photo_author' %>
    </div>
<% end %>

app/views/photos/new.html.erb
<% content_for :head do %>
Create New Photo
<% end %>
<%= render'photos_form' %>

app/views/photos/show.html.erb
<% content_for :head do %>
    Photo <%= @photo.id %>
<% end %>
<div class="col-md-12"></div>
<div class="row"><%= image_tag(@photo.url, class: 'col-md-12') %></div>
<div class="row">
  <%= content_tag :div, @photo.title, class: 'col-md-6 photo_title' %>
  <%= content_tag :div, @photo.author, class: 'col-md-6 photo_author' %>
</div>
<div class="row">
  <div class="col-md-12">
    <%= link_to ' Edit', edit_photo_path(@photo), class: 'btn btn-warning fa fa-edit' %>
    <%= link_to ' Delete', @photo, method: :delete, class: 'btn btn-danger fa fa-trash' %>
    <%= link_to ' All Photos', photos_path, class: 'btn btn-primary fa fa-list' %>
  </div>
</div>